### PR TITLE
Improved annotation field parsing

### PR DESCRIPTION
**Pull request by FelixMoelder**
This PR separates the ANN-field to create a more detailed and cleaner table.
Additionally, google and ensemble lookups have been added.

### CODE REVIEW

**Comment by jrobinso** [comment]
@FelixMoelder thanks for the PR.  Can you zip and attach an example file I can use to test this with?

@brianjohnhaas @johanneskoester any comments on this?

**Comment by johanneskoester** [comment]
LGTM, you have to see how this looks like in your default template though. We are using a custom one now, which moves parts of the table to a detail view.

**Comment by jrobinso** [comment]
The Genecards link is problematic because of their license,  "Free for academic non-profit institutions. Other users need a Commercial license".

**Comment by jrobinso** [comment]
OK, very nice.  I'm merging this, bug in the future we might consider adding a command line template of some time for the search engine.   Google is blocked in China.

**Comment by FelixMoelder** [comment]
Thanks!
Would you mind to create another release for us?

**Pull request merged**
