### PR TITLE
Add utility to change default zoom

### PR DESCRIPTION
**Pull request by DevangThakkar**
Currently the zoom is set to the default of 40 (I believe this stems from the minimum bases being 39 but I have not verified) such that using only a single position (chr5	474989) results in a 41bp window (chr5:474,969-475,009). I added an argument that allows users to change this value. The default is set to 40, so the current output is maintained in the absence of this argument. 

Let me know if you have any comments.

### CODE REVIEW

**Comment by jrobinso** [comment]
There's already a flanking argument, see the readme.

**Comment by DevangThakkar** [comment]
Yes, I see that. If I understand correctly, that allows the user to have a set number of bases around the location show up in the html file. What this does is actually set the zoom. If you look at the example [here](https://igvteam.github.io/igv-reports/examples/example_vcf.html), the flanking was set to 1000 and that can seen in the fact that the html contains 500 bases on each side, but the initial zoom is 41. Now consider the attached file where the zoom was added using the --zoom argument and set to 300. The flanking is still 1000. 
I had to edit the extension to allow uploading but you can change it and see if it makes sense. [example_vcf.html.txt](https://github.com/user-attachments/files/15856061/example_vcf.html.txt)

**Comment by jrobinso** [comment]
OK,  I don't have any time for igv-reports at the moment but keep this open.

**Comment by jrobinso** [comment]
Sorry for the delay.   This looks like a good addition.   I have just a couple of suggestions.  
* Rename the "zoom" argument to "window".  Zoom is used internally in igv.js to mean something else.  I'm open to other name suggestions.
* Default the value to None, not 40, and if it is None leave the current behavior as is.   As coded here it actually changes behavior when start & end are specified.     Also, there could be a difference in igv.js between zooming to a single nucleotide and zooming to a window around that nucleotide, although the visual effect is the same.   In any event I don't want to change behavior in any way if this optional argument is not specified.

**Comment by DevangThakkar** [comment]
That makes sense! I've added in the requested naming changes, and added code to allow for a None default for the argument. Let me know what you think.

**Comment by jrobinso** [comment]
Looks good

**Pull request merged**
